name: Git Mirror Action
author: Thomas Edwards
description: Mirror between two independent repositories
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:  
  target_repo:
    description: Target repo full url
    required: true      
  github_token:
    description: GitHub token for temporary authenication
    required: true      
  repository_owner:
    description: Source repository owner
    required: true
  repository:
    description: Source repository name
    required: true  
  target_ssh_private_key:
    description: SSH key used to authenticate with destination ssh url provided (optional if public or https url with authentication)
    required: false
  target_ssh_username:
    description: SSH useranme
    required: false    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:        
    TARGET_SSH_PRIVATE_KEY: ${{ inputs.target_ssh_private_key }}
    TARGET_SSH_USERNAME: ${{ inputs.target_ssh_username }}
  args:    
    - ${{ inputs.target_repo }}
    - ${{ inputs.github_token }}
    - ${{ inputs.repository_owner }}
    - ${{ inputs.repository }}